spring:
  datasource:
    url: jdbc:derby:memory:myDb;create=true
    username: sa
    password: sa
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
